name: Build Process

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Validate changelog
        run: |
          set -x
          git log --oneline | head -n10
          make lint-commit-messages

